# Generated by Django 4.1.4 on 2022-12-11 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_watchlist_platform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streamplatform',
            old_name='about',
            new_name='About',
        ),
        migrations.RenameField(
            model_name='streamplatform',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='streamplatform',
            old_name='website',
            new_name='Website',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='platform',
            new_name='Platform',
        ),
    ]
