# Generated by Django 4.1.4 on 2022-12-13 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0006_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
